/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录签发token
         * @description 校验账号密码，签发JWT。失败统一返回401，不区分用户不存在/密码错误。
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blend/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 调配煤优化器
         * @description 运行配煤优化：GA(scikit-opt)寻优 + 质量预测模型(LightGBM)评估 + SHAP解释。
         *
         *     返回3套方案：cost_optimal / quality_stable / balanced（4.1.5输出规范）。
         *     优化器本体在 models/blending_optimizer/，此处只做参数校验与调用编排。
         */
        post: operations["optimize_blend_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blend/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 历史配煤方案查询
         * @description 查询PostgreSQL blend_recipe表（3.4.1节），支持按焦炉号过滤。
         */
        get: operations["list_recipes_blend_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blend/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 化验结果回流，触发增量学习
         * @description 化验数据闭环（4.1.7节）：
         *
         *     1. 取该批次当时的预测值 → 2. 计算误差 → 3. 超阈值写入误差缓冲区(Redis)
         *     → 4. 缓冲区满 BUFFER_TRIGGER_SIZE 条触发增量微调（LightGBM热启动，小学习率防遗忘）。
         */
        post: operations["feedback_blend_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/furnace/temp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 实时炉温
         * @description 查询TDengine中该焦炉最近一次的机/焦侧火道温度。
         *
         *     注意：换向前后2~3分钟数据为脏数据（4.2.6节），
         *     由ETL管道打标记，此处查询应过滤 switching_flag=0。
         */
        get: operations["get_temp_furnace_temp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/furnace/ai-setpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * AI设定值建议
         * @description MPC求解最优煤气流量/吸力设定值（4.2.4节），输出前经 clamp_setpoint 钳位。
         *
         *     shadow模式下仅展示不下发；auto模式由控制回路消费本接口结果。
         */
        get: operations["get_ai_setpoint_furnace_ai_setpoint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/furnace/control-mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 切换控制模式
         * @description 切换 manual/shadow/auto。
         *
         *     状态存Redis（key: furnace:control_mode:{furnace_id}），Redis不可用时落内存。
         *     注意：「一键切手动」为DCS硬切换（4.2.6节），本接口只是AI系统侧的模式记录，
         *     不构成安全通路。
         */
        post: operations["set_control_mode_furnace_control_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/furnace/k-coefficients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 热工K系数查询
         * @description 返回K均/K安/K1/K2/K3（4.2.6节统一考核口径）。
         *
         *     计算逻辑在 data/pipeline/k_coefficients.py（直行温度记录+推焦计划/执行记录），
         *     本接口只做查询编排。
         */
        get: operations["get_k_coefficients_furnace_k_coefficients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdm/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 监控设备列表
         * @description 返回监控设备清单，支持按优先级P0/P1/P2过滤。
         */
        get: operations["list_devices_pdm_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdm/devices/{device_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 设备健康评分
         * @description 综合健康评分（0~100）：孤立森林异常分 + LSTM趋势外推 + ISO 10816振动分级。
         *
         *     模型在 models/pdm/（anomaly_detect/trend_forecast），此处做调用编排。
         */
        get: operations["get_health_pdm_devices__device_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pdm/alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * PdM告警列表
         * @description 查询两级预警告警（4.3.2节：level1实时异常 / level2趋势+ISO10816分级）。
         */
        get: operations["list_alarms_pdm_alarms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vision/alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 视觉告警列表
         * @description 查询视觉告警，支持按场景/确认状态过滤，按时间倒序。
         */
        get: operations["list_alarms_vision_alarms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vision/alarms/{alarm_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 视觉告警确认
         * @description 确认告警：记录处理人与处置意见；误报标记回流训练集迭代（每周重训消费）。
         */
        post: operations["ack_alarm_vision_alarms__alarm_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 健康检查：自身存活 + 依赖（PostgreSQL/Redis/TDengine）连通性。
         *
         *     依赖不可达时返回 degraded 而非 500，便于负载均衡探活与运维定位。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AckRequest
         * @description 告警确认请求。
         */
        AckRequest: {
            /**
             * Handler
             * @description 处理人
             */
            handler: string;
            /**
             * Comment
             * @description 处置意见
             * @default
             */
            comment: string;
            /**
             * Is False Positive
             * @description 是否误报（回流用于模型迭代）
             * @default false
             */
            is_false_positive: boolean;
        };
        /**
         * CoalInfo
         * @description 可用煤种信息（含库存约束与化验指标）。
         */
        CoalInfo: {
            /** Coal Id */
            coal_id: number;
            /** Name */
            name: string;
            /**
             * Stock Tons
             * @description 库存量 吨
             */
            stock_tons: number;
            /**
             * Price Per Ton
             * @description 单价 元/吨
             */
            price_per_ton: number;
            /**
             * Min Ratio
             * @description 配比下限（工艺约束）
             * @default 0
             */
            min_ratio: number;
            /**
             * Max Ratio
             * @description 配比上限（工艺约束）
             * @default 1
             */
            max_ratio: number;
            /**
             * Lab Data
             * @description 化验指标：Ad/Vdaf/St_d/G/Y/Rmax等
             */
            lab_data?: Record<string, never>;
        };
        /**
         * ControlModeRequest
         * @description 控制模式切换请求。
         */
        ControlModeRequest: {
            /**
             * Furnace Id
             * @description 焦炉编号
             */
            furnace_id: number;
            /** Mode */
            mode: string;
            /**
             * Operator
             * @description 操作人工号/姓名（审计用）
             */
            operator: string;
            /**
             * Reason
             * @description 切换原因
             * @default
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LabFeedback
         * @description 化验结果回流（4.1.7增量学习入口）。
         */
        LabFeedback: {
            /**
             * Batch No
             * @description 配煤批次号
             */
            batch_no: string;
            /**
             * Actual Quality
             * @description 实测焦炭质量：M25/M10/CSR/CRI
             */
            actual_quality: Record<string, never>;
        };
        /**
         * LoginRequest
         * @description 登录请求体。
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * OptimizeRequest
         * @description 配煤优化请求（4.1.5输入JSON）。
         */
        OptimizeRequest: {
            target_quality: components["schemas"]["TargetQuality"];
            /** Available Coals */
            available_coals: components["schemas"]["CoalInfo"][];
            /**
             * Max Cost Per Ton
             * @default 1500
             */
            max_cost_per_ton: number;
            /**
             * Priority
             * @default cost
             */
            priority: string;
        };
        /**
         * TargetQuality
         * @description 目标焦炭质量指标。
         */
        TargetQuality: {
            /**
             * M25 Min
             * @description 抗碎强度M25下限 %
             * @default 90
             */
            M25_min: number;
            /**
             * M10 Max
             * @description 耐磨强度M10上限 %
             * @default 6.5
             */
            M10_max: number;
            /**
             * Csr Min
             * @description 反应后强度CSR下限 %
             * @default 65
             */
            CSR_min: number;
            /**
             * Cri Max
             * @description 反应性CRI上限 %
             * @default 25
             */
            CRI_max: number;
        };
        /**
         * TokenResponse
         * @description 登录响应体。
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_blend_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recipes_blend_recipes_get: {
        parameters: {
            query?: {
                furnace_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_blend_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabFeedback"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_temp_furnace_temp_get: {
        parameters: {
            query: {
                furnace_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_setpoint_furnace_ai_setpoint_get: {
        parameters: {
            query: {
                furnace_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_control_mode_furnace_control_mode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_k_coefficients_furnace_k_coefficients_get: {
        parameters: {
            query: {
                furnace_id: number;
                shift_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_pdm_devices_get: {
        parameters: {
            query?: {
                priority?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_pdm_devices__device_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alarms_pdm_alarms_get: {
        parameters: {
            query?: {
                level?: string | null;
                device_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alarms_vision_alarms_get: {
        parameters: {
            query?: {
                /** @description 场景过滤: helmet/fire_smoke/intrusion/gas_leak/meter_reading/coke_maturity */
                scene?: string | null;
                /** @description 是否已确认 */
                acked?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alarm_vision_alarms__alarm_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alarm_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
